### ISSUE TITLE
perf: aws batch workflow performance improvement

### ISSUE THREAD

**Issue by niyiyu** [SeisSCOPED/QuakeScope#1]
To document my test this afternoon. Jobs are submitted to run phase picking on SCEDC and NCEDC data.

Time: Jan 1 to Dec 31, 2012. **366 days in total**
Network: CI, NC, BK, NP. **2030 stations in total**
Each job runs on: 50 days, 40 stations. **408 jobs in total**

Some pricing hint. FARGATE SPOT (4 vCPU + 8 GB RAM, $0.0617/h). This will cost 408 job x 11 hr x $0.0617 = **$277 for CI/NC/BK/NP in 2012**. Very possibly, the actual number will be much lower because no data for many of the stations.

On the other hand, most jobs are running smoothly, until they are terminated after 100 minutes. Several are failed because S3 got too busy, or SPOT interruption. The following improvements should be implemented.

- [x] Empirically, limit the compute environment vCPU no larger than ~~300~~ **500**. Above this number, either SCEDC or NCEDC will not responding, and the following error will be raised and job will be terminated. It is even better to set a smaller number because there will be other users on SCEDC/NCEDC data. **We may steadily increase this number when our job efficiency has been improved.**
- [x] #7
- [x] #8
```
Traceback (most recent call last):
...
    File "/usr/local/lib/python3.12/site-packages/aiobotocore/client.py", line 412, in _make_api_call
        raise error_class(parsed_response, operation_name)
        botocore.exceptions.ClientError: An error occurred (503) when calling the HeadObject operation (reached max retries: 4): Service Unavailable
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
...
    File "/code/src/picker.py", line 615, in <module>
        main()
    File "/code/src/picker.py", line 139, in main
        picker.run_picking()
...
    File "/code/src/picker.py", line 539, in _load_data
        async for stream in self.s3.load_waveforms():
...
    File "/code/src/picker.py", line 291, in _read_waveform_from_s3
        with fs.open(uri) as f:
```
- [x] #6
- [x] #2
- [x] #3
- [x] #5

**Comment by yetinam** [comment]
A few thoughts on the points you mention:

- Regarding rate limits, all jobs hold a queue of data. At start-up, they'll try filling their queue as quickly as possible, so they'll be hammering the S3. Maybe adding a little bit of delay here might already help, because once the queues have been populated, the rates should go down. In any case, an exponential backoff scheme for the loading would also implicitly do this. Best case it doesn't even increase the total job duration because of the internal queue. We might want to check the queue size is appropriate though.
- It should be possible to write a token into a database for each station-day picked, so that on startup a job can check if part of it's task have already been completed. Then we can just set batch to restart jobs that were killed due to SPOT interruptions.

As another remark, maybe the development should happen on a new branch so we don't break this repository in the way it's used for the tutorial? Or we move the tutorial version somewhere else.

**Comment by niyiyu** [comment]
> * Regarding rate limits, all jobs hold a queue of data. At start-up, they'll try filling their queue as quickly as possible, so they'll be hammering the S3. Maybe adding a little bit of delay here might already help, because once the queues have been populated, the rates should go down. In any case, an exponential backoff scheme for the loading would also implicitly do this. Best case it doesn't even increase the total job duration because of the internal queue. We might want to check the queue size is appropriate though.

Most of the S3 service interruption did not happen at the beginning of the job. In fact, they happened in the middle of the workflow, sporadically. 

But it is still necessary we implement something to scatter the request.
  - Delay time at the beginning of the job.
  - It should also be noticed that there are jobs that will get no data at all through its lifetime, but they constantly send s3 request trying to open the file. Use one single `fs.ls` or `fs.glob` request to list files that exist, instead of trying all station-component pair.

> * It should be possible to write a token into a database for each station-day picked, so that on startup a job can check if part of it's task have already been completed. Then we can just set batch to restart jobs that were killed due to SPOT interruptions.

Yes, agreed. 

> As another remark, maybe the development should happen on a new branch so we don't break this repository in the way it's used for the tutorial? Or we move the tutorial version somewhere else.

Your last commit was tagged as `tutorial_v1`. The notebook is now moved to `tutorials/`.

**Comment by yetinam** [comment]
Perfect! And yes, adding an ls or glob call before sound like a good idea.
